version: '{build}-{branch}'

branches:
  # whitelist
  only:
    - master

clone_depth: 50


init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\$env:TARGET\craft\bin\craft.py" $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    mkdir C:\CraftMaster | Out-Null
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --branch v0.2 --depth=1 git://anongit.kde.org/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & C:\python36\python.exe C:\CraftMaster\CraftMaster\CraftMaster.py --config $env:APPVEYOR_BUILD_FOLDER\appveyor.ini --target $env:TARGET
    craft -p gammaray
    craft nsis
    craft --install-deps gammaray


build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER gammaray

#test_script:
#- ps: |
#    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test gammaray


on_success:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --package gammaray
    Get-ChildItem C:\CraftMaster\$env:TARGET\tmp\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

on_finish:
- ps: |
    Get-ChildItem $env:USERPROFILE\.craft\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    Push-AppveyorArtifact C:\CraftMaster\$env:TARGET\etc\kdesettings.ini.dump

environment:
    matrix:
    - TARGET: msvc2015x86
    - TARGET: mingw
    - TARGET: msvc2015x64

