# SPDX-FileCopyrightText: 2024 Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: MIT

name: Create release

on:
  workflow_dispatch:
    inputs:
      sha1:
        type: string
        required: true
        description: "sha1 to be tagged"
      version:
        type: string
        required: true
        description: "Desired numeric version (without any prefix/suffix)"

permissions:
  contents: write
  actions: write

jobs:
  create_release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout CI tools
        uses: actions/checkout@v4
        with:
          repository: KDABLabs/ci-release-tools
          path: ci-release-tools
          ref: main

      - name: Setup git author name
        run: |
          git config --global user.email "github_actions@kdab"
          git config --global user.name "KDAB GitHub Actions"

      - name: Create release
        run: |
          python3 ci-release-tools/src/create_release.py --repo Gammaray --version ${{ github.event.inputs.version }} --sha1 ${{ github.event.inputs.sha1 }} --repo-path .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
